FROM python:3.7

WORKDIR /opt/app

# Copy the current directory contents into the container
ADD . /opt/app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Specifically for OpenCV
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

# Run
CMD ["python", "worker.py"]
