FROM python:3.7

WORKDIR /opt/app

# Copy the current directory contents into the container
ADD . /opt/app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Run
CMD ["python", "host.py"]
