version: '3'

services:
  host:
    build:
      context: .
      dockerfile: Dockerfile.host
    networks:
      - pdk-net
    depends_on:
      - redisdb
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    networks:
      - pdk-net
    depends_on:
      - redisdb
    env_file:
      - .env

  redisdb:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - pdk-net
    volumes:
      - redis_data:/data/redis

networks:
  pdk-net:

volumes:
  redis_data:
